name: Synchronize to forked repo
on:
  push:
    branches:
      - main
      - dev

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.AUTO_VERCEL }}
          fetch-depth: 0
          ref: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'main' || 'dev' }}


      - name: Add remote-url
        run: |
          git remote add forked-repo https://escape1001:${{ secrets.AUTO_VERCEL }}@github.com/escape1001/dalim_front
          git config user.name escape1001
          git config user.email es.c.ape1001@hanmail.net
      
      - name: Push changes to forked-repo 
        run: |
          git push -f forked-repo ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && 'main' || 'dev' }}
      
      - name: Clean up
        run: |
          git remote remove forked-repo